// Filter values copied from the API documentation. meta_data.json uses a
// different id space for series and brands than listings.json, so these
// lists are the source of truth for the listings filters.

export const ITEM_TYPES = [
  { value: "mlb_card", label: "Player cards" },
  { value: "stadium", label: "Stadiums" },
  { value: "equipment", label: "Equipment" },
  { value: "sponsorship", label: "Sponsorships" },
  { value: "unlockable", label: "Unlockables" },
] as const

export const RARITIES = ["diamond", "gold", "silver", "bronze", "common"] as const

export const POSITIONS = [
  "SP",
  "RP",
  "CP",
  "C",
  "1B",
  "2B",
  "3B",
  "SS",
  "LF",
  "CF",
  "RF",
] as const

export const TEAMS = [
  ["FA", "Free Agents"],
  ["BAL", "Orioles"],
  ["BOS", "Red Sox"],
  ["NYY", "Yankees"],
  ["TB", "Rays"],
  ["TOR", "Blue Jays"],
  ["CWS", "White Sox"],
  ["CLE", "Guardians"],
  ["DET", "Tigers"],
  ["KC", "Royals"],
  ["MIN", "Twins"],
  ["HOU", "Astros"],
  ["LAA", "Angels"],
  ["OAK", "Athletics"],
  ["SEA", "Mariners"],
  ["TEX", "Rangers"],
  ["ATL", "Braves"],
  ["MIA", "Marlins"],
  ["NYM", "Mets"],
  ["PHI", "Phillies"],
  ["WAS", "Nationals"],
  ["CHC", "Cubs"],
  ["CIN", "Reds"],
  ["MIL", "Brewers"],
  ["PIT", "Pirates"],
  ["STL", "Cardinals"],
  ["ARI", "Diamondbacks"],
  ["COL", "Rockies"],
  ["LAD", "Dodgers"],
  ["SD", "Padres"],
  ["SF", "Giants"],
] as const

export const CARD_SETS = [
  { value: "legend", label: "Legends" },
  { value: "flashback", label: "Flashbacks" },
] as const

export const SORTS = [
  { value: "rank", label: "Rank" },
  { value: "best_sell_price", label: "Buy now price" },
  { value: "best_buy_price", label: "Sell now price" },
] as const

export const SERIES = [
  [1337, "Live"],
  [10001, "Rookie"],
  [10002, "Breakout"],
  [10003, "Veteran"],
  [10004, "All-Star"],
  [10005, "Awards"],
  [10006, "Postseason"],
  [10009, "Signature"],
  [10011, "Cover Athletes"],
  [10013, "Prime"],
  [10017, "Topps Now"],
  [10018, "Finest"],
  [10020, "2nd Half Heroes"],
  [10022, "Milestone"],
  [10028, "World Baseball Classic"],
  [10032, "Hall of Fame"],
  [10033, "Subway"],
  [10034, "Standout"],
  [10035, "The Negro Leagues"],
  [10038, "Pipeline"],
  [10039, "Spring Breakout"],
  [10043, "Egg Hunt"],
  [10044, "Contributor"],
  [10045, "Last Ride"],
  [10046, "Jolt"],
  [10047, "Spotlight"],
  [10048, "Moonshot"],
  [10049, "Cornerstone"],
  [10050, "New Threads"],
  [10052, "Ranked 1000"],
  [10062, "St. Patrick's Day"],
  [10068, "Mexico City"],
  [10065, "Cityscapes"],
  [10064, "Mural"],
  [10066, "Vintage"],
  [10054, "Summer"],
  [10056, "2026 All-Star"],
  [10058, "2026 Draft"],
  [10057, "2026 Home Run Derby"],
  [10070, "Field of Dreams"],
  [10059, "MLBx"],
  [10061, "The Show Classics"],
  [10072, "2026 Postseason"],
] as const

export const BRANDS = [
  [0, "Ritual"],
  [1, "Louisville Slugger"],
  [2, "Marucci"],
  [3, "Mizuno"],
  [4, "Rawlings"],
  [5, "Nike"],
  [6, "Franklin"],
  [7, "Under Armour"],
  [8, "Wilson"],
  [9, "Sam Bat"],
  [10, "All-Star"],
  [11, "EvoShield"],
  [12, "Old Hickory"],
  [13, "Trinity Bat Co"],
  [14, "Adidas"],
  [15, "New Balance"],
  [16, "Lizard Skins"],
  [17, "STANCE"],
  [18, "Varo"],
  [19, "Bat Skin"],
  [20, "SSK"],
  [21, "Axe"],
  [22, "Jordan"],
  [23, "Victus"],
  [24, "Easton"],
  [25, "Tater"],
  [26, "44 Pro"],
  [27, "Dinger"],
  [28, "G-Form"],
  [29, "B45"],
  [30, "Oakley"],
  [31, "100% Eyewear"],
  [32, "ASICS"],
  [33, "Birdman"],
  [34, "Chandler"],
  [35, "Warstic"],
  [36, "Absolutely Ridiculous"],
  [37, "Cooperstown Bat Co"],
  [38, "BWP"],
  [39, "New Era"],
  [40, "Force3 Pro Gear"],
  [41, "Bruce Bolt"],
  [42, "Diamond Kinetics"],
  [43, "My Legacy"],
] as const

// The docs list slot_type_id as 0-14 without names.
export const SLOT_TYPE_IDS = Array.from({ length: 15 }, (_, i) => i)

// The market takes a 10% cut of every completed sale.
export const MARKET_TAX = 0.1
